### ISSUE TITLE
Dashboard Views Lost After Update to @flowfuse/node-red-dashboard

### ISSUE THREAD

**Issue by Koneisto** [FlowFuse/node-red-dashboard#1539] opened 2024-12-16 19:03 UTC
### Current Behavior

After updating to the latest version of @flowfuse/node-red-dashboard, all dashboards (pages) were marked as orphaned, and the views were completely lost. This is not the first time such an issue has occurred after an update. It severely disrupts workflows and raises concerns about the stability of this module.

### Steps To Reproduce

	1.	Update to the latest version of @flowfuse/node-red-dashboard and node-red 4.0.6
	2.	Open the Node-RED editor after the update.
	3.	Observe that all dashboard views (pages) are marked as orphaned.
	4.      No pages, no dashboard.

### Environment

- Dashboard version: 1.20.0
- Node-RED version: 4.0.6
- Platform/OS: Latest official docker image minimal

**Comment by bartbutenaers** [comment] 2024-12-17 23:28
@Koneisto 

I did not have time to reproduce your problem, but could you please explain what you mean with orphaned?  If you have screenshot perhaps from that time that would help.  Thanks!

Although I am not familiar with that part of the dashboard, so perhaps I won't be able to assist you with this one.  But perhaps it does ring a bell to anybody else, to pinpoint which PR caused this...

> raises concerns about the stability of this module.

It is very easy to predict what will happen in fact: there are now 322 open issues in this repo. As long (near) nobody from our community starts solving them, those Github issues will keep causing issues in your dashboard...

**Comment by bartbutenaers** [comment] 2024-12-19 19:13
@Koneisto ,
Thanks for the detailed instructions!!!

> A warning appeared: “You have some unused configuration nodes.”

Could your problem perhaps be related to [this](https://github.com/node-red/node-red/issues/4999) issue, which has been registered in the Github repo of Node-RED itself?  Hopefully it is, because Nick is going to look at that one tomorrow...

**Comment by GogoVega** [comment] 2024-12-20 11:30
Should be fixed in 4.0.8

**Closed as completed** 2024-12-21 20:09 UTC
Labels: type:bug, needs-triage
