### ISSUE TITLE
DB2 \ Layout \ Pages keeps resetting to expanded view.

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#797] opened 2024-04-24 08:39 UTC
### Current Behavior

In the Dashboard 2 \ Layout tab, the Pages view keeps resetting to an all expanded view after a change is saved.

### Expected Behavior

The Page view keeps the Pages \ Groups as the user set it before anything is changed.

### Steps To Reproduce

Create 20 pages, and within each page create 30 groups.
Add a button element to page 20, Group 28.
Close (>) all Groups on all pages, close (>) all Pages.
Edit Page 20, edit some setting and Update.

The Page list is now fully expanded again.

### Environment

- Dashboard version: 1.7.1
- Node-RED version: 3.17.1
- Node.js version: 18.19.0
- npm version:
- Platform/OS:
- Browser: Edge, Firefox, Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by colinl** [comment] 2024-04-24 08:48
Indeed this is annoying.  I thought there was already an open issue for it, but I cannot find it.

**Comment by arturv2000** [comment] 2024-04-25 00:13
There is #660

**Comment by joepavitt** [comment] 2024-04-25 14:03
Closing as duplicate of #682

**Closed by joepavitt** 2024-04-25 14:03 UTC
Labels: bug, needs-triage
