### ISSUE TITLE
ui-switch value bug

### ISSUE THREAD

**Issue by i8beef** [FlowFuse/node-red-dashboard#356] opened 2023-11-20 05:12 UTC
### Description

1. The `ui-switch` node appears to be outputting the OFF value when switching off correctly, but ALSO outputs the OFF values when switching it ON.
2. The UI indicator seems to get stuck to "on" in the node-red editing interface for me too...
3. Dashboard 1 had an option for the "Indicator" to represent the value of the last input, or the last output... my understanding is the one here ALWAYS represents the last "input" value yes?

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by colinl** [comment] 2023-11-20 08:12
I think points 1 and two are a duplicate of #311 

For point 3, I believe the "state of input/output" Indicator field will be supported at some point. See #318

**Closed** 2023-11-20 08:30 UTC
Labels: needs-triage, feature-request

**Comment by colinl** [comment] 2023-11-20 09:47
Also, for point 3 see #210
