### ISSUE TITLE
FR: Notification: display center as Modal\Lightbox

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#732] opened 2024-04-03 10:44 UTC
### Description

When displaying a Notification on the center of the page, a user still has access to the dashboard below. It would be very helpfull to be able to display a (center or all) Notification in such a way that access to the dashboard page is not possible anymore until the Notification disappears (either by user action or on time-out).

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment] 2024-04-03 10:54
Duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/193 and https://github.com/FlowFuse/node-red-dashboard/issues/627

**Closed by joepavitt** 2024-04-03 10:54 UTC
Labels: needs-triage, feature-request
