### ISSUE TITLE
Chart: complete chart data is not send out

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#723] opened 2024-03-30 17:27 UTC
### Current Behavior

the chart outputs just the input message added with a `datapoint` but not the complete stored data of the chart.

### Expected Behavior

the complete chart is sent out in a format that can be stored and, after a restart, could be fed into the chart again to get a persistent chart.
Also this could help as a template in crafting complete charts.

### Steps To Reproduce

write sensor data with each reading to to chart as a pair of `topic` and `payload`.

### Environment

- Dashboard version: 1.6.1
- Node-RED version: 3.1.8
- Node.js version: 
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment] 2024-04-03 08:45
Duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/229

**Closed by joepavitt** 2024-04-03 08:45 UTC
Labels: bug, needs-triage
