### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by scargill** [FlowFuse/node-red-dashboard#550] opened 2024-02-06 13:31 UTC
### Description

In dashboard 1 we have node-red-contrib-ui-led - very useful - any chance of adding one of those - changes colours depending input....

### Properties

- Labelling
- Style
- Behaviour

### Events

- **on-action**: this widget would need to send a message back to Node-RED when it's action is triggered, e.g. button clicked
- **on-change**: this widget would need to send a message back to Node-RED when it's value is changed/updated

### Controls

- **enabled**: this widget can be enabled/disabled
- **visible**: this widget can be hidden

### Existing Examples

We use Vuetify for a lot of our widgets, is there a Vuetify component that is similar to what you are looking for?

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by colinl** [comment] 2024-02-06 17:24
> * **on-action**: this widget would need to send a message back to Node-RED when it's action is triggered, e.g. button clicked
> * **on-change**: this widget would need to send a message back to Node-RED when it's value is changed/updated

ui-led does not have those features does it?  I thought it was display only.

**Comment by scargill** [comment] 2024-02-06 17:28
UI-LED is display only. For example I use it to show the state of a light or other device controlled by a button – but it’s a moot point since the buttons don’t yet seem to allow for custom state-dependent colour and icon – until then I have to stick with dashboard 1.

 

Regards

 

Pete

 

Peter Scargill

https://tech.scargill.net

Calle Ceuta 14

Galera

Granada 18840

Spain

+34 634 326331

**Comment by joepavitt** [comment] 2024-02-16 13:49
Closing as duplicate of #423

**Closed by joepavitt** 2024-02-16 13:49 UTC
Labels: needs-triage, feature-request, widget
