### ISSUE TITLE
Form widget does not allow initialising of the form field contents by passing in a message

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#363] opened 2023-11-22 10:14 UTC
It should be possible to send a message to the form node to preload the form fields with data.

Probably the format of the message should be the same as the message that the node sends when submit is clicked.

**Comment by joepavitt** [comment] 2024-06-23 15:35
Closing as duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/1000 which is about to be closed/completed with https://github.com/FlowFuse/node-red-dashboard/pull/1016

**Closed by joepavitt** 2024-06-23 15:35 UTC
