### ISSUE TITLE
ui-chart line points missing

### ISSUE THREAD

**Issue by gtnscebba** [FlowFuse/node-red-dashboard#1308] opened 2024-09-19 06:27 UTC
### Current Behavior

I represent some values as lines in ui-chart. 
Although all values ​​are present in the msg.payload, the second element of all series is not represented and there is a hole in its place.
More information has been provided in the NodeRed forum, at this [link](https://discourse.nodered.org/t/ui-chart-line-point-missing/91090).
The workaround is to repeat twice the msg.payload.
A note: this behaviour is very similar to an old problem with bar chart solved in release 1.15.

### Expected Behavior

It should not be necessary to repeat the data to be represented twice.

### Steps To Reproduce

I attach an export of a function ad ui-chart. The exported function has two times the node.send(msg) (lines 80-81)
Regarding the data, each array used contains twelve numeric items (such as [21.68,22.96,22.96,22.64,22.96,22.88,23.2,23.04,22.8,22.96,23.04,22.96]).

[flows.json](https://github.com/user-attachments/files/17054535/flows.json)

### Environment

- Dashboard version:  1.16.0
- Node-RED version:  4.0.2
- Node.js version:  20.17
- npm version: 10.8.2
- Platform/OS: Raspberry PI4b+ with SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02)
- Browser:  Chrome 128.0.6613.138 (64 bit)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by colinl** [comment] 2024-09-19 08:37
Unfortunately your flow cannot be run because it relies on global data.  Please replace the global data with example inline code in order that the flow can be run in order to see the problem.

**Comment by gtnscebba** [comment] 2024-09-19 10:12
Colin, 
I attach a new export. It doesn't use global variables.
Is it okay for you?
Ciao

[NR_ticket_ui-chart.json](https://github.com/user-attachments/files/17057401/NR_ticket_ui-chart.json)

**Comment by colinl** [comment] 2024-09-19 20:50
Did you realise that you are drawing the lines in reverse order?  So the values of giorno start at 19 and go down to 8?  I suspect that is at least part of the problem.

**Comment by gtnscebba** [comment] 2024-09-20 05:29
Colin,
this behavior is intended. The array is populated by automatic flows putting the newest value at the head (in element [0]), scrolling all the other elements.
When displayed on ui-chart, however, the value is presented in reverse mode.
If I represent the array in the same sequence, the "hole" is at the head instead of at the end. I've already tried.
Of course, even in that case, if you double the msg.payload, the hole disappears.
This problem is the exact same behavior that was in the case of bar chars that was solved with version 1.15 of the dashboard.

**Comment by colinl** [comment] 2024-09-20 08:39
> If I represent the array in the same sequence, the "hole" is at the head instead of at the end

In that case it seems that this is duplicate of #1279, which has been fixed and should therefore be in the next release.

**Comment by gtnscebba** [comment] 2024-09-20 14:29
Colin,
I have installed the palette 1.17.0 and the "hole" is still present.
The only new thing is that now there are two lines without holes, while before there was only one.
If I double the msg.payload there are no holes, as for version 1.16.0.
If you want, you can try again with the flow I already sent you. I think, therefore, that 1.17 has not solved the problem.

Questo è il risultato con la palette 1.17.0.

![image](https://github.com/user-attachments/assets/17fcdcca-0139-4c2f-a0b5-26d7c8b1ec50)

**Comment by colinl** [comment] 2024-09-20 15:07
Did you refresh the browser page?

**Comment by gtnscebba** [comment] 2024-09-20 16:37
Yes, of course.
I have also deleted cache.

**Comment by colinl** [comment] 2024-09-20 17:00
Does it still fail if you add the data from left to right rather than right to left?

**Comment by gtnscebba** [comment] 2024-09-21 05:25
Yes Colin, it is the same.
Of course, you have the hole at left, as you can see:

![image](https://github.com/user-attachments/assets/b8bff0f7-b528-4411-980e-629dc5d1a2a9)

**Comment by colinl** [comment] 2024-09-21 08:45
I can confirm that I see this too, with the flow posted above.

**Comment by colinl** [comment] 2024-09-21 14:40
Your example flow is very complex and not easy to understand.  It would make this problem much easier to investigate if you very much simplified the issue such that you have just a sequence of messages, for only a couple of the series.  You can use an Inject node to inject an array of payloads, which you feed through a Split node to convert it to individual messages which you feed to the chart.  It is only necessary to provide the failing messages.

**Comment by gtnscebba** [comment] 2024-09-22 06:22
Colin,
I have simplified the flow a lot.
The data is sent to the ui-chart node when it is created.
So, the msg.payload contains only and exclusively a single json that represents the value of a point.
I attach the new flow for your analysis.
Despite this, to have all the complete lines, the message related to the element [0] must be repeated twice. If you omit it, the line has a "hole" between the point [0] and the point [1]. 

I explain what I do do send a data to ui-chart. Look here:

```
dati = {
        "tipo": "Cronot.",
        "giorno": giorno,
        "valore": t_crono[i]
    };
    msg.payload = dati;
    node.send(msg);
    if (i == 0) node.send(msg);
```

The variable "dati" represents a point to be visualized on the graph. 

As you can see, the ui-chart node expects to receive a "tipo" key for which I insert the name of the line (temperature of a room), a "giorno" key for the X-axis and a "valore" key for the Y-axis.
When I create the single json object I put it in the msg.payload and send it to ui-chart via node.send.

As you can see, after the node.send(msg) there is an "if": if I am processing the item [0], I do an additional node.send(msg).
In this way I see the 6 complete lines; if I omitted the if, only two lines are complete, the other 4 are broken.

With this code, the result is:

![image](https://github.com/user-attachments/assets/83ae52fa-cc78-420c-a02a-98cfde67140a)

The data to be represented are injected by an inject node, that creates 6 messages.

**Comment by colinl** [comment] 2024-09-22 10:38
I was hoping you would create a flow something like this that shows the problem.  I have done it for you.

@gayanSandamal would it be appropriate for you to have a look at this?  It appears to be very similar to #1255, but is still seen in 1.17.0

![image](https://github.com/user-attachments/assets/c7143a71-155a-4778-9e3c-db893930af15)

```
[{"id":"33347fc4eb8c7b53","type":"ui-chart","z":"997da33a0beedade","group":"086177714ce3990f","name":"Temperature Stanze","label":"Temp casa ultimi 16 gg (alle 12:05)","order":1,"chartType":"line","category":"tipo","categoryType":"property","xAxisLabel":"Giorni","xAxisProperty":"giorno","xAxisPropertyType":"property","xAxisType":"linear","xAxisFormat":"","xAxisFormatType":"auto","yAxisLabel":"Temperatura","yAxisProperty":"valore","ymin":"","ymax":"","action":"append","stackSeries":false,"pointShape":"line","pointRadius":4,"showLegend":true,"removeOlder":1,"removeOlderUnit":"3600","removeOlderPoints":"","colors":["#1f77b4","#aec7e8","#ff7f0e","#e30d23","#98df8a","#cc28d7","#ff9896","#9467bd","#c5b0d5"],"textColor":["#666666"],"textColorDefault":true,"gridColor":["#e5e5e5"],"gridColorDefault":true,"width":"10","height":"7","className":"","x":720,"y":7780,"wires":[[]]},{"id":"b8d7460309a257dc","type":"split","z":"997da33a0beedade","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","property":"payload","x":470,"y":7780,"wires":[["33347fc4eb8c7b53","876d8792847f5e65"]]},{"id":"6402c64eef8d08a1","type":"inject","z":"997da33a0beedade","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[[],{\"tipo\":\"Cronot.\",\"giorno\":22,\"valore\":22.3},{\"tipo\":\"Letto\",\"giorno\":22,\"valore\":22.8},{\"tipo\":\"Studio\",\"giorno\":22,\"valore\":22},{\"tipo\":\"Cronot.\",\"giorno\":21,\"valore\":22.5},{\"tipo\":\"Letto\",\"giorno\":21,\"valore\":23.28},{\"tipo\":\"Studio\",\"giorno\":21,\"valore\":21.84},{\"tipo\":\"Cronot.\",\"giorno\":20,\"valore\":22.6},{\"tipo\":\"Letto\",\"giorno\":20,\"valore\":23.44},{\"tipo\":\"Studio\",\"giorno\":20,\"valore\":22}]","payloadType":"json","x":320,"y":7780,"wires":[["b8d7460309a257dc"]]},{"id":"086177714ce3990f","type":"ui-group","name":"Group1","page":"0956c4073e2cdfa6","width":"12","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"0956c4073e2cdfa6","type":"ui-page","name":"Testing","ui":"ID-BASE-1","path":"/test-dash2","icon":"progress-wrench","layout":"flex","theme":"4c9d95876fd3a57d","order":17,"className":"","visible":true,"disabled":false},{"id":"ID-BASE-1","type":"ui-base","name":"Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-control","ui-notification","ui-gauge-classic"],"showPageTitle":true,"titleBarStyle":"default"},{"id":"4c9d95876fd3a57d","type":"ui-theme","name":"Light","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```
![image](https://github.com/user-attachments/assets/c2f755fc-6d2b-42cb-be33-8d6466a9ed87)

**Comment by gtnscebba** [comment] 2024-09-22 16:51
Colin,
thank you.
As you can see, even your example shows that the orange "Studio" line has a hole between day 21 and day 22, even though the data is present.
I imagine that FlowFuse will investigate this problem is one following release.

**Comment by colinl** [comment] 2024-09-22 20:40
> even your example shows that the orange "Studio" line has a hole between day 21 and day 22

There would not have been much point in my posting a flow that did not show the problem.

**Closed** 2024-09-23 13:17 UTC
Labels: size:S - 2, bug
