### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by egs2003** [FlowFuse/node-red-dashboard#566] opened 2024-02-10 20:11 UTC
### Description

It should be possible to fix the sidebar. Possibly in all three variants via the settings. Permanently displayed without the option to collapse it, collapsed by default and expanded by default.  Perhaps also the option of horizontal or vertical or right / left / top / bottom.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment] 2024-02-13 11:51
Closing as is duplicate of #549

**Closed** 2024-02-15 16:43 UTC
Labels: needs-triage, feature-request
