### ISSUE TITLE
Create multiple dashboard instances

### ISSUE THREAD

**Issue by dsl400** [FlowFuse/node-red-dashboard#876] opened 2024-05-19 20:16 UTC
### Description

The goal is to create multiple dashboards 

mysite/ui/main_dashboard
mysite/ui/second_dashboard

the instances should be completely independent  and the url segment should be defined by the creator

**Comment by joepavitt** [comment] 2024-05-21 08:06
Appreciate the issue, will close though as it's a duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/23

it's a very difficult topic, but something we know is of high value, so it's high up our list.

**Closed by joepavitt** 2024-05-21 08:06 UTC
Labels: needs-triage, feature-request
