### ISSUE TITLE
cubicInterpolationMode Tension Paramter for UIChart

### ISSUE THREAD

**Issue by ghwaldo** [FlowFuse/node-red-dashboard#1338] opened 2024-09-27 09:37 UTC
### Description

uichart.js is capable of setting parameters so that a line chart is smoothened (bezier).
In my opinion it would be nice if one could set addition parameter to the chart node to do such things.

Thnx for this great work.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment] 2024-09-27 17:28
Thanks @ghwaldo - I'm going to close this as a duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/384, but will push that up the priority as a result of your request.

**Closed by joepavitt** 2024-09-27 17:28 UTC
Labels: needs-triage, feature-request
