### ISSUE TITLE
Error running When Dashboard 2.0 on Bosch Ctrlx Core

### ISSUE THREAD

**Issue by BrockWilkinson** [FlowFuse/node-red-dashboard#563] opened 2024-02-09 16:31 UTC
The pallete installs successfully, but when I add any dashboard element and navigate to the dashboard url it is blank. When I inspect the page it shows the following error. 
index-j47xBCGS.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by joepavitt** [comment] 2024-02-14 11:26
I believe whatever is causing this, is also the cause of a problem when running Dashboard 2.0 in Home Assistant too

**Comment by BrockWilkinson** [comment] 2024-02-15 17:02
Ok, let me know if theres anything I can do to assist. Would it be of benefit for me to upload the file associated with the error?

**Comment by joepavitt** [comment] 2024-02-15 17:15
Thanks @BrockWilkinson fairly sure we know the problem, as its linked to other issues reported with Home Automation hosted Dash boards too. Will try to sort this tomorrow

**Comment by joepavitt** [comment] 2024-02-21 16:45
With #595 and #581 merged, I want to get a sanity check if our next release (which will contain these fixes) will then resolve this issue too.

**Comment by joepavitt** [comment] 2024-02-22 17:56
@BrockWilkinson just published the `1.2.0` release, which I'm hoping resolves this - please let me know when you get a chance to test it out.

**Comment by BrockWilkinson** [comment] 2024-02-22 19:48
I now see the loading screen when I try to access the dashboard, but it doesn't load and I repeatedly get the same two error messages in the console.
A GET 404 (Not Found) error and a SIO connect Error: xhr poll error.

My console log is attached.

[console-1708631040479.log](https://github.com/FlowFuse/node-red-dashboard/files/14378628/console-1708631040479.log)

**Comment by joepavitt** [comment] 2024-02-23 08:38
Thanks Brock - that is at least progress. That means that our HTTP connection to Node-RED is establishing correctly. 

#526 was meant to cover this, looking at the logs you've sent though, it seems they're appending a `/node-red` _before_ the `/dashboard`, instead of in-place of (which @hardillb and I had bagged on being the case).

I'm not too familiar with CtrlX so not 100% how much control is made available to the proxy options? Is that all covered under the covers?

**Comment by joepavitt** [comment] 2024-02-23 08:45
Just to write out our logic with the paths you've got in place:

* `/node-red/dashboard/...` is the HTTP path being used.
* `/node-red/node-red/dashboard/socket.io/` is what SocketIO is _trying_ to connect to, which for some reason has an extra `/node-red` in the path

Ah, I think we may have re-broken the #437 with the "fix" for #526 - I can reproduce the problem locally. Will get a fix in shortly.

**Closed** 2024-02-23 10:57 UTC
Labels: bug
