### ISSUE TITLE
Gauge widget text and pointer confused by menu popout

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#587] opened 2024-02-18 10:00 UTC
### Description

The gauge text and pointer cabn be confused by the page dropdown popout.  For example, before clicking on the hamburger I see

![image](https://github.com/FlowFuse/node-red-dashboard/assets/38307/6b4a6a29-ae41-40d0-bcb8-157995fcdfa7)

When I click the hamburger I see

![image](https://github.com/FlowFuse/node-red-dashboard/assets/38307/0c0814d1-4f40-4a6a-9e56-9173110d158a)

This is using NR 3.1.5, D2 1.1.0.  No errors in the developer console.
I notice that the window has to be wide for popout to shift the display rather then overlying it.  The problem is only seen in the shift mode.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by hotNipi** [comment] 2024-02-19 08:25
Noted, explained and potential fix suggested here: https://github.com/FlowFuse/node-red-dashboard/issues/560

**Comment by joepavitt** [comment] 2024-02-21 14:13
Closing as duplicate of #560

**Closed by joepavitt** 2024-02-21 14:13 UTC
Labels: epic
